---
title: "Unimodal ONA Models (location, dialogue) for Monash University"
output:
  html_document:
    df_print: paged
editor_options: 
  chunk_output_type: inline
---
```{r, setup, include=FALSE, echo=FALSE}
# Set local working directory
# setwd("~/Desktop/epistemic_analytics/Monash_collab")
```
```{r, setup, include=FALSE, echo=FALSE}
knitr::opts_knit$set(root.dir = '~/Documents/GitHub/Monash_collab')
```
# 0. Initialize dependencies 
```{r, echo = FALSE, message = FALSE}
# Reinstallation sequence for ONA package
# remove.packages("ona")
# remove.packages("tma")
# # install.packages("ona", repos = c("https://epistemic-analytics.gitlab.io/qe-packages/ona/cran/", "https://cran.rstudio.org"))
# install.packages("~/Documents/GitHub/Monash_collab/ona_0.1.1.tar.gz", repos = NULL, type = "source")
# install.packages("~/Documents/GitHub/Monash_collab/tma_0.1.2.tar.gz", repos = NULL, type = "source")

# Load necessary libraries 
library(rENA)
library(ona) 
library(tma)
library(readxl)
library(tidyverse)
# Source plotter code
# source("~/Desktop/epistemic_analytics/Monash_collab/code/ona_plotter_monash.R")
```

# 1. Read in and process dataset
```{r, message = FALSE}
# Note: Using updated version from monash_ona_tma.Rmd, after two new location codes were added
df_location <- read.csv("~/Desktop/epistemic_analytics/Monash_collab/data/with_phases.csv") %>%
  filter(modality == "location") %>%
  as.data.frame()

df_dialogue <- read.csv("~/Desktop/epistemic_analytics/Monash_collab/data/with_phases.csv") %>%
  filter(modality == "dialogue") %>%
  as.data.frame()
```

# 2. Specify parameters: Units, codes, metadata, and Horizon-of-observation rules
```{r}
# Specify unit columns 
unit_cols <- c("session_id", "phase", "initiator", "comparison") 

# Cumulative code columns. Can split these up into location-based and utterance-based. Will be differently grouped after encoding modalities
location_code_cols <- c("collaborate_primary", "independent_primary", "collaborate_secondary", "independent_secondary", "task_distribution", "task_transition", "independent_distraction", "collaboration_on_distraction")

dialogue_code_cols <- c("task_allo_and_plann", "provision_of_handover_information","info_sharing_and_situ_assess", "escalation", "information_requesting", "responding_to_request", "agreement")

# Store metadata (duration will  leave this later once we compare active and continuing impacts) 
meta_cols <- c("session_id", "initiator", "comparison", "utterance_id", "conversation_id", "text", "duration", "receiver", "location", "priority", "communication_type", "stage_based_on_num_of_student", "stage_based_on_scenario")
  
# Establish HOO rules. Units are making connections only in their respective sessions 
HOO_rules_model <-  tma:::rules(
    session_id %in% UNIT$session_id & phase %in% UNIT$phase & conversation_id %in% UNIT$conversation_id
)
context_model_location <- tma:::contexts(
  x = df_location,
  units = unit_cols,
  hoo_rules = HOO_rules_model
)
context_model_dialogue <- tma:::contexts(
  x = df_dialogue,
  units = unit_cols,
  hoo_rules = HOO_rules_model
)
```

# 2. Accumulate 
```{r}
accum_location <- tma:::accumulate_contexts (
    x = context_model_location,
    codes = location_code_cols,
    weight.by = function(x) { x },
    decay.function = function(x) {
        return(x<(FULL_CONTEXT[ROWS]$end_time - FULL_CONTEXT[ROWS]$start_time + 20))*1
      },
    time.column = "start_time", 
    return.ena.set = FALSE
) 


accum_dialogue <- tma:::accumulate_contexts (
    x = context_model_dialogue,
    codes = dialogue_code_cols,
    weight.by = function(x) { x },
    decay.function = function(x) {
        return(x<(FULL_CONTEXT[ROWS]$end_time - FULL_CONTEXT[ROWS]$start_time + 10))*1
      },
    time.column = "start_time", 
    return.ena.set = FALSE
) 

my_location_rotation.params <-
  list(low_perf=accum_location$meta.data$comparison == "low",
       high_perf=accum_location$meta.data$comparison == "high")

my_dialogue_rotation.params <-
  list(low_perf=accum_dialogue$meta.data$comparison == "low",
       high_perf=accum_dialogue$meta.data$comparison == "high")
```

# 3. Generate the ONA Set

## 3.1 Perform MR 
```{r}
ona_location_set <-
  model(accum_location,                                 # The previously run accumulation above
        rotate.using ="mean",                  # Function provided by ONA
        rotation.params = my_location_rotation.params   # The defined paremeters for rotation
        )
ona_dialogue_set <-
  model(accum_dialogue,                                 # The previously run accumulation above
        rotate.using ="mean",                  # Function provided by ONA
        rotation.params = my_dialogue_rotation.params   # The defined paremeters for rotation
        )
# ona_location_set <-
#   model(accum_location
#         )
# ona_dialogue_set <-
#   model(accum_dialogue
#         )
```

# 4. Analyze Model

## 1) Goodness of fit
```{r}
# Pearson's R
ona_location_gof <- ona:::correlations(ona_location_set)$pearson
ona_location_gof[[1]]
ona_dialogue_gof <- ona:::correlations(ona_dialogue_set)$pearson
ona_dialogue_gof[[1]]
```
## 2) Variance explained
SVD1
```{r}
# Variance explained by MR1 
ona_location_mr <- lm(ona_location_set$points$MR1 ~ ona_location_set$points$comparison) %>% summary()
ona_location_mr$r.squared
ona_dialogue_mr <- lm(ona_dialogue_set$points$MR1 ~ ona_dialogue_set$points$comparison) %>% summary()
ona_dialogue_mr$r.squared
```
## 3) Interpretive Alignment
```{r}
source("~/Desktop/epistemic_analytics/Monash_collab/code/ona_plotter_monash.R")
# Plot ONA plots
make.ona.plot(ona_location_set, 
              "Monash Location Model", 
              flip_x = TRUE)
make.ona.plot(ona_dialogue_set,
              "Monash Dialogue Model")
```

```{r}
library(effsize)
cohen.d(ona_location_set$points$comparison$low$MR1, ona_location_set$points$comparison$high$MR1)
cohen.d(ona_dialogue_set$points$comparison$low$MR1, ona_dialogue_set$points$comparison$high$MR1)

```


```{r}
colSums(ona_dialogue_set$line.weights$comparison$low)
```


```{r}
colSums(ona_dialogue_set$line.weights$comparison$high)
```


```{r}
colSums(ona_dialogue_set$line.weights)
```


