---
title: "Multimodal ONA Model for Monash University"
output:
  html_document:
    df_print: paged
editor_options: 
  chunk_output_type: inline
---

```{r, setup, include=FALSE, echo=FALSE}
# Set local working directory
# setwd("~/Desktop/epistemic_analytics/Monash_collab")
```

```{r, setup, include=FALSE, echo=FALSE}
knitr::opts_knit$set(root.dir = '~/Documents/GitHub/Monash_collab')
```

# 0. Initialize dependencies 
```{r, echo = FALSE, message = FALSE}
# Reinstallation sequence for ONA package
# remove.packages("ona")
# install.packages("ona", repos = c("https://epistemic-analytics.gitlab.io/qe-packages/ona/cran/", "https://cran.rstudio.org"))
# remove.packages("tma")
# install.packages("tma", repos = c("https://epistemic-analytics.gitlab.io/qe-packages/tma/cran/", "https://cran.rstudio.org"))

# Load necessary libraries 
library(rENA)
library(ona) 
library(tma)
library(readxl)
library(tidyverse)
# Source plotter code
# source("~/Desktop/epistemic_analytics/Monash_collab/code/ona_plotter_monash.R")
```

# 1. Read in and process dataset
```{r}
# Note: Reran this for new dataset
df <- read_excel("~/Desktop/epistemic_analytics/Monash_collab/data/merged_A_15_added_phases.xlsx") %>% as.data.frame()
names(df) <- gsub(" ", "_", tolower(names(df)))
df['comparison'][df['comparison'] == 0] <- "low"
df['comparison'][df['comparison'] == 1] <- "high"
colnames(df)[which(names(df) == "cp")] <- "collaborate_primary"
colnames(df)[which(names(df) == "ip")] <- "independent_primary"
colnames(df)[which(names(df) == "cs")] <- "collaborate_secondary"
colnames(df)[which(names(df) == "is")] <- "independent_secondary"
colnames(df)[which(names(df) == "td")] <- "task_distribution"
colnames(df)[which(names(df) == "tt")] <- "task_transition"
colnames(df)[which(names(df) == "id")] <- "independent_distraction"
colnames(df)[which(names(df) == "cd")] <- "collaboration_on_distraction"

df <- df[, -c(1)]
write.csv(df, "~/Desktop/epistemic_analytics/Monash_collab/data/with_phases.csv", row.names = FALSE)
View(df)
```

```{r, message = FALSE}

df <- read_csv("~/Desktop/epistemic_analytics/Monash_collab/data/with_phases.csv") %>% as.data.frame()
# df
```

# 2. Specify parameters: Units, codes, metadata, and Horizon-of-observation rules
```{r}
# Specify unit columns 
unit_cols <- c("session_id", "phase", "initiator", "comparison") 

# Cumulative code columns. Can split these up into location-based and utterance-based. Will be differently grouped after encoding modalities
code_cols <- c("collaborate_primary", "independent_primary", "collaborate_secondary", "independent_secondary", "task_distribution", "task_transition", "independent_distraction", "collaboration_on_distraction", "task_allo_and_plann", "provision_of_handover_information","info_sharing_and_situ_assess", "escalation", "information_requesting", "responding_to_request", "agreement")

# Store metadata (duration will  leave this later once we compare active and continuing impacts) 
meta_cols <- c("session_id", "initiator", "comparison", "utterance_id", "conversation_id", "text", "duration", "receiver", "location", "priority", "communication_type", "stage_based_on_num_of_student", "stage_based_on_scenario")
  
# Establish HOO rules. Units are making connections only in their respective sessions and conversations
HOO_rules_model <-  tma:::rules(
    session_id %in% UNIT$session_id & phase %in% UNIT$phase & conversation_id %in% UNIT$conversation_id
)
```

## 3. Define contexts based on HOO rules
```{r}
context_model <- tma:::contexts(
  x = df,
  units = unit_cols,
  hoo_rules = HOO_rules_model
)
```

# 4. Build ONA multimodal model 
```{r}
# Define accumulation function
ona_multimodal_tif_accum <- tma:::accumulate_contexts (
    x = context_model,
    codes = code_cols,
    weight.by = function(x) { x },
    # Define the decay function to account differently for location and dialogue--arbitrary values that assume location is more continually impacting and dialogue is more actively impacting 
    decay.function = function(x) {
      mod <- FULL_CONTEXT[RESPONSE_INDEX, ]$modality
      if(mod == "location")
        # return(x<=20)*1
        return(x<(FULL_CONTEXT[ROWS]$end_time - FULL_CONTEXT[ROWS]$start_time +20))*1
      if(mod == "dialogue")
        # return(x<=10)*1
        return(x<(FULL_CONTEXT[ROWS]$end_time - FULL_CONTEXT[ROWS]$start_time +10))*1
      else
        return(0)
      },
    time.column = "start_time", 
    return.ena.set = FALSE,
    mode.column = "modality"
) 
my_rotation.params <-
  list(low_perf=ona_multimodal_tif_accum$meta.data$comparison == "low",
       high_perf=ona_multimodal_tif_accum$meta.data$comparison == "high")

# Make ONA set
ona_multimodal_tif_set <-
  model(ona_multimodal_tif_accum,                                 # The previously run accumulation above
        rotate.using ="mean",                  # Function provided by ONA
        rotation.params = my_rotation.params   # The defined paremeters for rotation
        )
# set <- ona_multimodal_tif_set
```

```{r}
# sum(as.matrix(ona_multimodal_tif_accum$connection.counts)[,"agreement & responding_to_request"])
# sum(as.matrix(ona_multimodal_tif_accum$connection.counts)[,"responding_to_request & agreement"])
# 
# sum(as.matrix(ona_multimodal_tif_set$connection.counts)[,"agreement & responding_to_request"])
# sum(as.matrix(ona_multimodal_tif_set$connection.counts)[,"responding_to_request & agreement"])
# 
# sum(as.matrix(ona_multimodal_tif_set$line.weights)[,"agreement & responding_to_request"])
# sum(as.matrix(ona_multimodal_tif_set$line.weights)[,"responding_to_request & agreement"])
```


# 5. Analyze model 
## 1) Goodness of fit
```{r}
# Pearson's R
ona_multimodal_tif_gof <- ona:::correlations(ona_multimodal_tif_set)$pearson
ona_multimodal_tif_gof[[1]]
```
## 2) Variance explained
```{r}
ona_multimodal_tif_MR <- lm(ona_multimodal_tif_set$points$MR1 ~ ona_multimodal_tif_set$points$comparison) %>% summary()
ona_multimodal_tif_MR$r.squared
```
## 3) Interpretive Alignment
```{r}
source("~/Desktop/epistemic_analytics/Monash_collab/code/ona_plotter_monash.R")
# Plot ONA plot
make.ona.plot(ona_multimodal_tif_set, 
              "Monash Multimodal Model", 
              flip_x = TRUE)
```

```{r}
library(effsize)
cohen.d(ona_multimodal_tif_set$points$comparison$low$MR1, ona_multimodal_tif_set$points$comparison$high$MR1)
```




